/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.radartest;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Radartest extends AbstractRadartest { 
	public Radartest(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
