/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'anatali' at '05/08/16 15.35' with Gradle 2.14.1
 *
 * @author anatali, @date 05/08/16 15.35
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    //Added by AN
    public static void main(String[] args) throws Exception {
    	System.out.println("Hello World!");
    }
}
