import alice.tuprolog.Term;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'anatali' at '05/08/16 16.39' with Gradle 2.14.1
 *
 * @author anatali, @date 05/08/16 16.39
 */

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    //Added by AN
    public String getTermInfo(){
    	Term tt = Term.createTerm("a(1)");
    	return tt.toString();
    }
    
    public static void main(String[] args){
    	System.out.println("Hello from Library " + new Library().getTermInfo());
    }
}
